EU-OSHA/osha-website

docroot/sites/all/modules/osha/osha/osha.info
docroot/sites/all/modules/osha/osha/osha.views_default.inc

File size was added to JSON view at /admin/structure/views/view/data_export/edit/page_publication

cw-1225 Add file size in publication JSON feed

---

docroot/sites/all/modules/osha/osha_blog/osha_blog.info
docroot/sites/all/modules/osha/osha_blog/osha_blog.views_default.inc
docroot/sites/all/modules/osha/osha_migration/content.blog.migrate.inc

The Summary (description field in CSV) wasn't migrated and the views are now modified to display Summary (if is empty will display the Body)

cw-1234 migrate blog summary

---

docroot/sites/all/modules/osha/osha_breadcrumbs/osha_breadcrumbs.path_breadcrumbs.inc

Create breadcrumbs for Footer pages and for Contact Form page.

cw-1242 footer pages breadcrumb

---

docroot/sites/all/modules/osha/osha_infographics/osha_infographics.module
docroot/sites/all/modules/osha/osha_migration/content.infographics.migrate.inc
docroot/sites/all/modules/osha/osha_migration/osha_migration.info
docroot/sites/all/modules/osha/osha_migration/osha_migration.module

Folderul infographics este in \\nas\PHP\osha\data\export-local

Cw migrate infographics

---

docroot/sites/all/modules/osha/osha/osha.install

Add Menu Position Rule for:
http://osha-corp-staging03.mainstrat.com/en/inside-eu-osha/governance-eu-osha/internal_documents/document_register (it is linked from http://osha-corp-staging03.mainstrat.com/en/inside-eu-osha/governance-eu-osha/internal_documents)

cw-1305 Governance Internal Document Articles

---

docroot/sites/all/modules/osha/osha/osha.module

Remove the "Delete" button from the node edit forms

cw-1337 Hide Delete Button

---

docroot/sites/all/modules/osha/osha_blog/osha_blog.module
docroot/sites/all/themes/osha_frontend/template.php

La introducerea unui noi comentariu sau la reply-ul unui comentariu existent, headerul trebuie sa fie tot cel de la blog. De asemenea, am fixat si breadcrumb-ul din respectiva pagina.

cw-1264 Blog Header and Breadcrumb

---

docroot/sites/all/modules/osha/osha_contact/osha_contact.module

Replace Topic dropdown list with input type text.

cw-contact-topic-text

---

docroot/sites/all/modules/osha/osha_migration/images.migrate.inc
docroot/sites/all/modules/osha/osha_migration/utils.api.inc

Am luat valoarea campului aliases asa cum vine ea din csv, dar din ce am observat, in images.txt campul aliases este gol.

cw-1395 Images Redirect

---

docroot/sites/all/modules/osha/osha_migration/content.articles.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.blog.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.blog_comments.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.board_bureau_members.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.calls.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.case_study.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.directives.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.focal_points.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.fop_pages.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.guidelines.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.highlight.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.infographics.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.job_vacancies.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.news.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.note_to_editor.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.press_release.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.publications.migrate.inc
docroot/sites/all/modules/osha/osha_migration/content.seminars.migrate.inc
docroot/sites/all/modules/osha/osha_migration/files.migrate.inc
docroot/sites/all/modules/osha/osha_migration/images.migrate.inc
docroot/sites/all/modules/osha/osha_migration/utils.api.inc

Otherwise the Wiki migration dies.

Fixed migration to show errors instead of dying when migration files are missing

---

docroot/sites/all/modules/contrib/entityreference_view_widget/entityreference_view_widget.api.php
docroot/sites/all/modules/contrib/entityreference_view_widget/entityreference_view_widget.css
docroot/sites/all/modules/contrib/entityreference_view_widget/entityreference_view_widget.info
docroot/sites/all/modules/contrib/entityreference_view_widget/entityreference_view_widget.js
docroot/sites/all/modules/contrib/entityreference_view_widget/entityreference_view_widget.module
docroot/sites/all/modules/contrib/entityreference_view_widget/views/entityreference_view_widget.views.inc
docroot/sites/all/modules/contrib/entityreference_view_widget/views/entityreference_view_widget.views_default.inc
docroot/sites/all/modules/contrib/entityreference_view_widget/views/entityreference_view_widget_handler_field_checkbox.inc
docroot/sites/all/modules/contrib/entityreference_view_widget/views/entityreference_view_widget_plugin_display.inc

Am facut update la modulul entityreference_view_widget si pare sa functioneze bine si selectarea de additional resources, dar si butonul de Browse de la Cover Image.
Nu stiu care este procedura de update modul pe mainstrat, dar aici sunt fisierele noului modul sau se poate face "drush up entityreference_view_widget" pe mainstrat.

cw-1439 Fix Additional Resources Select

---

docroot/sites/all/modules/osha/osha/tmgmt/osha_tmgmt.drush.inc
docroot/sites/all/modules/osha/osha/tmgmt/osha_tmgmt.install
docroot/sites/all/modules/osha/osha/tmgmt/sources/locale/osha_tmgmt_locale.ui.inc

We need to run ``osha-tmgmt-blacklist-literals`` to send the bad strings into the void

Implemented string blacklist feature

---

docroot/sites/all/modules/osha/osha_infographics/osha_infographics.install

Alias-urile sunt corectate de la forma "O/png/infographic_5_NO_v1.0.png"  la "png/infographic_5_NO_v1.0.png" si este setat si language-ul corespunzator.

cw-1437 Correct Infographics Aliases

---

docroot/sites/all/modules/osha/osha_workflow/osha_workflow.module

Previously the node was marked dirty only when was published

Added option to reindex the node on any status change

---

scripts/s9/post-update.php

cw-1479 Webform Url Alias and Breadcrumb

---

scripts/s9/post-update.php

- Enable Captcha
- Fieldset-ul cu captcha, dupa enable, o sa fie ascuns din CSS, cred ca trebuie sa modifice ceva Ivan la asta

cw-1479 add captcha

---

docroot/sites/all/modules/contrib/fapi_validation/LICENSE.txt
docroot/sites/all/modules/contrib/fapi_validation/README.txt
docroot/sites/all/modules/contrib/fapi_validation/fapi_validation.info
docroot/sites/all/modules/contrib/fapi_validation/fapi_validation.module
docroot/sites/all/modules/contrib/fapi_validation/tests/fapi_validation.test
docroot/sites/all/modules/contrib/fapi_validation/tests/fapi_validation_tests.info
docroot/sites/all/modules/contrib/fapi_validation/tests/fapi_validation_tests.module
docroot/sites/all/modules/osha/osha_contact/osha_contact.module

cw-1597 Contact Form validation

---

docroot/sites/all/modules/osha/osha/osha.views_default.inc

Pe osha.edw.ro am facut modificarea aceasta, dar pe mainstrat nu pot sa modific modific setarile campului Image:
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: http://osha-corp-staging03.mainstrat.com/en/admin/structure/views/ajax/config-item/data_export/page_news/field/field_image
StatusText: error

cw-data-export-view Fix Image Field Settings

---

docroot/sites/all/themes/osha_frontend/css/osha_theme_default.css
docroot/sites/all/themes/osha_frontend/js/menu_expand.js

Scriptul din hoverhref.js nu pare sa fie folosit pe nicaieri, dar am fixat CSS-ul si JS-ul din menu_expand.js.

MC-19 Fix javascript and css

---

docroot/sites/all/modules/osha/osha_events/osha_events.info
docroot/sites/all/modules/osha/osha_events/osha_events.views_default.inc

Am descoperit doar la /oshevents si /admin/content/events ca lipseste numarul de rezultate intoarse de cautare, iar la restul de view-uri este prezent.

MC-35 Display search number of results

---

docroot/sites/all/modules/osha/osha_publication/osha_publication.features.fe_block_settings.inc
docroot/sites/all/modules/osha/osha_publication/osha_publication.info
docroot/sites/all/modules/osha/osha_publication/osha_publication.install

Release for Staging from develop - 2016.02.10

---

docroot/sites/all/modules/osha/osha_publication/osha_publication.install

Release for production 2016.02.11

Release for production 2016.02.11

---

docroot/sites/all/modules/osha/osha/tmgmt/osha_tmgmt.module

fixes some bugs in _osha_tmgmt_create_english_translations:
* not all translations properly created
* pdf files were being removed by file_field_update for a translation job with multiple target languages

MDR-767 bugfix

---

docroot/sites/all/modules/osha/osha_dangerous_substances/osha_dangerous_substances.features.wysiwyg.inc

Paste from word button

---

docroot/includes/bootstrap.inc
docroot/includes/request-sanitizer.inc

https://www.drupal.org/sa-core-2018-002
https://cgit.drupalcode.org/drupal/rawdiff/?h=7.x&id=2266d2a83db50e2f97682d9a0fb8a18e2722cba5

Apply patch for sa-core-2018-002
